### ISSUE TITLE
Wish to refund EOS deposit to eosio.rex

### ISSUE THREAD

**Issue by hibkim0** [EOSIO/eosio.system#42]
Last week I made unintentional wrong operation to eosio.rex - deposit of 5 eos to eosio.rex.  The operation was performed through normal Chrome web browser on eosauthority.com site.  A few times I tried to take back my eos from eosio.rex but eosio.rex only shows zero balance to be refunded every time.   Please let know how to take it back.  Thanks.

![private_wrong-opr-eos](https://user-images.githubusercontent.com/19411557/115503066-d1a30e00-a2b0-11eb-8ea1-b0aecbc67aec.PNG)

**Comment by deckb** [comment]
This issue is more relevant to the system contract repo.

When depositing into REX there is a lockup period. Looking at the `rexbal` for your account 

```
cleos get table eosio eosio rexbal -L ha2dknrtgage -l 1
{
  "rows": [{
      "version": 0,
      "owner": "ha2dknzxguge",
      "vote_stake": "0.0000 EOS",
      "rex_balance": "0.3429 REX",
      "matured_rex": 0,
      "rex_maturities": [{
          "key": "2106-02-07T06:28:15",
          "value": 3429
        }
      ]
    }
  ],
  "more": true,
  "next_key": "7603369544524404896"
}
```

It looks like you deposited into the REX savings account and will need to move it out of your REX savings using the action `mvfrmsavings`. I would reach out to EOS Authority to see how to call that action with their wallet.

**Comment by hibkim0** [comment]
Thank you very much, deckb!  I will look forward to your support with this issue.

**Comment by hibkim0** [comment]
> This issue is more relevant to the system contract repo.
> 
> When depositing into REX there is a lockup period. Looking at the `rexbal` for your account
> 
> ```
> cleos get table eosio eosio rexbal -L ha2dknrtgage -l 1
> {
>   "rows": [{
>       "version": 0,
>       "owner": "ha2dknzxguge",
>       "vote_stake": "0.0000 EOS",
>       "rex_balance": "0.3429 REX",
>       "matured_rex": 0,
>       "rex_maturities": [{
>           "key": "2106-02-07T06:28:15",
>           "value": 3429
>         }
>       ]
>     }
>   ],
>   "more": true,
>   "next_key": "7603369544524404896"
> }
> ```
> 
> It looks like you deposited into the REX savings account and will need to move it out of your REX savings using the action `mvfrmsavings`. I would reach out to EOS Authority to see how to call that action with their wallet.

Thank you very much, deckb! I will look forward to your support with this issue.
