### ISSUE TITLE
My EOS balance is frozen and I can't move it to exchange

### ISSUE THREAD

**Issue by hibkim0** [EOSIO/eosio.system#43]
I don't know what I had done wrong but I keep facing a message saying "does not have signature for it.  
Please take a look at attached file and help me out!!

![private_eos_send_failure](https://user-images.githubusercontent.com/19411557/115951645-be947600-a51c-11eb-9275-b3167b11f3fd.PNG)

**Comment by deckb** [comment]
This not an issue specific to this  repo and so I will be closing it. I’ve provided some help below.

That error means that the private key you are using is not for ha2dknrtgage@active. I would confirm that the public key you are using matches that account.

**Comment by deckb** [comment]
Taking a quick look at bloks it looks like you usually use the owner key.

https://www.bloks.io/transaction/75a7020a189981eacf0535e850b6c9d2e041855eea9a2f7357cf0e089b113b8d

**Comment by hibkim0** [comment]
Someone told me that my account has been hacked and the ownership has been transferred to the hacker because my private key was disclosed.  If this is true, is there any way for me to get it restored?  Please help me out.

**Comment by deckb** [comment]
Apologies but this is not the forum for these types of questions. Please check in with the community on Telegram or ask here: https://forums.eoscommunity.org/
